/**
 * The drawings behind the names in `icon-names.ts`.
 *
 * Every icon is a named import, and that is the whole point of this file.
 * lucide-react also exports an object holding all of its icons and a loader
 * that fetches one by name at run time, and either would have made this a
 * three-line file: look the name up, draw what comes back. But the object
 * drags all eighteen hundred drawings into the editor's bundle, and the
 * loader fetches each one from the server as it is needed — which a
 * downloaded site, opened from disk with no JavaScript at all, cannot do.
 * Named imports put these hundred-odd into the bundle and nothing else, and
 * the component draws each as inline SVG, so the picture is in the page's
 * own markup and needs no network to appear.
 *
 * The type is what keeps the two files honest: a name added to the table in
 * `icon-names.ts` without a drawing here is a compile error, and so is a
 * drawing here for a name that is not there. The test goes one step further
 * and checks each drawing is the lucide export its name spells, so `phone`
 * cannot quietly be drawn as an envelope.
 */
import {
  Star, Heart, Check, CircleCheck, BadgeCheck, ShieldCheck, Zap, Sparkles, Rocket, Lightbulb,
  Target, Award, ThumbsUp, Phone, Mail, MessageCircle, MapPin, Globe, Clock, Calendar, House,
  Building, Store, Landmark, Accessibility, User, Users, Handshake, HeartHandshake,
  FaceSlightlySmiling, Baby, GraduationCap, Briefcase, BookOpen, FileText, ChartColumn, TrendingUp,
  Calculator, PiggyBank, Wallet, CreditCard, ShoppingCart, ShoppingBag, Gift, Tag, Scale, Gavel,
  Lock, Key, Truck, Package, Car, Bike, Plane, Bed, Tent, Mountain, Compass, Coffee, Utensils,
  ChefHat, Pizza, CakeSlice, Croissant, Wheat, Wine, Beer, Stethoscope, HeartPulse, Pill, Activity,
  Dumbbell, Brain, Eye, Scissors, Flower2, Hammer, Wrench, HardHat, PaintRoller, Ruler, Plug,
  Droplets, Flame, Snowflake, SprayCan, Sprout, Leaf, TreeDeciduous, Sun, Recycle, Dog, PawPrint,
  Camera, Image, Video, Music, Mic, Palette, PenTool, Megaphone, PartyPopper, Smartphone, Laptop,
  Monitor, Wifi, Code, Cloud, Settings, Search, Info, CircleQuestionMark, TriangleAlert, Download,
  ArrowRight,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "./icon-names";

export const ICON_SET: Record<IconName, LucideIcon> = {
  star: Star,
  heart: Heart,
  check: Check,
  "circle-check": CircleCheck,
  "badge-check": BadgeCheck,
  "shield-check": ShieldCheck,
  zap: Zap,
  sparkles: Sparkles,
  rocket: Rocket,
  lightbulb: Lightbulb,
  target: Target,
  award: Award,
  "thumbs-up": ThumbsUp,
  phone: Phone,
  mail: Mail,
  "message-circle": MessageCircle,
  "map-pin": MapPin,
  globe: Globe,
  clock: Clock,
  calendar: Calendar,
  house: House,
  building: Building,
  store: Store,
  landmark: Landmark,
  accessibility: Accessibility,
  user: User,
  users: Users,
  handshake: Handshake,
  "heart-handshake": HeartHandshake,
  "face-slightly-smiling": FaceSlightlySmiling,
  baby: Baby,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  "book-open": BookOpen,
  "file-text": FileText,
  "chart-column": ChartColumn,
  "trending-up": TrendingUp,
  calculator: Calculator,
  "piggy-bank": PiggyBank,
  wallet: Wallet,
  "credit-card": CreditCard,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  gift: Gift,
  tag: Tag,
  scale: Scale,
  gavel: Gavel,
  lock: Lock,
  key: Key,
  truck: Truck,
  package: Package,
  car: Car,
  bike: Bike,
  plane: Plane,
  bed: Bed,
  tent: Tent,
  mountain: Mountain,
  compass: Compass,
  coffee: Coffee,
  utensils: Utensils,
  "chef-hat": ChefHat,
  pizza: Pizza,
  "cake-slice": CakeSlice,
  croissant: Croissant,
  wheat: Wheat,
  wine: Wine,
  beer: Beer,
  stethoscope: Stethoscope,
  "heart-pulse": HeartPulse,
  pill: Pill,
  activity: Activity,
  dumbbell: Dumbbell,
  brain: Brain,
  eye: Eye,
  scissors: Scissors,
  "flower-2": Flower2,
  hammer: Hammer,
  wrench: Wrench,
  "hard-hat": HardHat,
  "paint-roller": PaintRoller,
  ruler: Ruler,
  plug: Plug,
  droplets: Droplets,
  flame: Flame,
  snowflake: Snowflake,
  "spray-can": SprayCan,
  sprout: Sprout,
  leaf: Leaf,
  "tree-deciduous": TreeDeciduous,
  sun: Sun,
  recycle: Recycle,
  dog: Dog,
  "paw-print": PawPrint,
  camera: Camera,
  image: Image,
  video: Video,
  music: Music,
  mic: Mic,
  palette: Palette,
  "pen-tool": PenTool,
  megaphone: Megaphone,
  "party-popper": PartyPopper,
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  wifi: Wifi,
  code: Code,
  cloud: Cloud,
  settings: Settings,
  search: Search,
  info: Info,
  "circle-question-mark": CircleQuestionMark,
  "triangle-alert": TriangleAlert,
  download: Download,
  "arrow-right": ArrowRight,
};
